import { UserTransactionHistory } from "@/lib/types/userType";

export const UserTransactionData: UserTransactionHistory[] = [
  {
    tRef: "Ref1",
    tName: "Transaction 1",
    tPrice: 100,
    tDate: new Date("2023-01-01"),
    providerId: "ProviderID1",
    providerName: "Provider 1",
    providerNumber: "1112223333",
    providerAddress: "101 Elm St",
  },
  {
    tRef: "Ref2",
    tName: "Transaction 2",
    tPrice: 200,
    tDate: new Date("2023-02-01"),
    providerId: "ProviderID2",
    providerName: "Provider 2",
    providerNumber: "2223334444",
    providerAddress: "202 Oak St",
  },
  {
    tRef: "Ref3",
    tName: "Transaction 3",
    tPrice: 300,
    tDate: new Date("2023-03-01"),
    providerId: "ProviderID3",
    providerName: "Provider 3",
    providerNumber: "3334445555",
    providerAddress: "303 Main St",
  },
  {
    tRef: "Ref4",
    tName: "Transaction 4",
    tPrice: 400,
    tDate: new Date("2023-04-01"),
    providerId: "ProviderID4",
    providerName: "Provider 4",
    providerNumber: "4445556666",
    providerAddress: "404 Maple St",
  },
  {
    tRef: "Ref5",
    tName: "Transaction 5",
    tPrice: 500,
    tDate: new Date("2023-05-01"),
    providerId: "ProviderID5",
    providerName: "Provider 5",
    providerNumber: "5556667777",
    providerAddress: "505 Pine St",
  },
  {
    tRef: "Ref6",
    tName: "Transaction 6",
    tPrice: 600,
    tDate: new Date("2023-06-01"),
    providerId: "ProviderID6",
    providerName: "Provider 6",
    providerNumber: "6667778888",
    providerAddress: "606 Elm St",
  },
  {
    tRef: "Ref7",
    tName: "Transaction 7",
    tPrice: 700,
    tDate: new Date("2023-07-01"),
    providerId: "ProviderID7",
    providerName: "Provider 7",
    providerNumber: "7778889999",
    providerAddress: "707 Oak St",
  },
  {
    tRef: "Ref8",
    tName: "Transaction 8",
    tPrice: 800,
    tDate: new Date("2023-08-01"),
    providerId: "ProviderID8",
    providerName: "Provider 8",
    providerNumber: "8889990000",
    providerAddress: "808 Maple St",
  },
  {
    tRef: "Ref9",
    tName: "Transaction 9",
    tPrice: 900,
    tDate: new Date("2023-09-01"),
    providerId: "ProviderID9",
    providerName: "Provider 9",
    providerNumber: "9990001111",
    providerAddress: "909 Pine St",
  },
  {
    tRef: "Ref10",
    tName: "Transaction 10",
    tPrice: 1000,
    tDate: new Date("2023-10-01"),
    providerId: "ProviderID10",
    providerName: "Provider 10",
    providerNumber: "1234567890",
    providerAddress: "1010 Oak St",
  },
];

const ProvidersInfo = [
  {
    fullName: "Service Provider 1",
    email: "provider1@example.com",
    password: "hashedpassword",
    address: "Argao, Cebu",
    role: "service_provider",
    profile: {
      firstName: "Provider",
      lastName: "User 1",
      contactNumber: "987-654-3210",
      location: "Argao, Cebu",
      description: "Experienced plumber offering reliable services.",
      profileImg: "https://randomuser.me/api/portraits/women/1.jpg",
    },
    ServiceCategory: ["Plumbing"],
    availability: [
      {
        dayOfWeek: "Monday",
        startTime: "09:00 AM",
        endTime: "05:00 PM",
      },
      {
        dayOfWeek: "Wednesday",
        startTime: "10:00 AM",
        endTime: "03:00 PM",
      },
    ],
    blockedTimeSlots: [],
  },
  {
    fullName: "Service Provider 2",
    email: "provider2@example.com",
    password: "hashedpassword",
    address: "Argao, Cebu",
    role: "service_provider",
    profile: {
      firstName: "Provider",
      lastName: "User 2",
      contactNumber: "987-654-3211",
      location: "Argao, Cebu",
      description: "Skilled electrician providing efficient services.",
      profileImg: "https://randomuser.me/api/portraits/women/2.jpg",
    },
    ServiceCategory: ["Electrical Repair"],
    availability: [
      {
        dayOfWeek: "Tuesday",
        startTime: "08:00 AM",
        endTime: "04:00 PM",
      },
      {
        dayOfWeek: "Thursday",
        startTime: "01:00 PM",
        endTime: "06:00 PM",
      },
    ],
    blockedTimeSlots: [],
  },
  {
    fullName: "Service Provider 3",
    email: "provider3@example.com",
    password: "hashedpassword",
    address: "Argao, Cebu",
    role: "service_provider",
    profile: {
      firstName: "Provider",
      lastName: "User 3",
      contactNumber: "987-654-3212",
      location: "Argao, Cebu",
      description: "Makeup artist specializing in various occasions.",
      profileImg: "https://randomuser.me/api/portraits/women/3.jpg",
    },
    ServiceCategory: ["Makeup Services"],
    availability: [
      {
        dayOfWeek: "Friday",
        startTime: "11:00 AM",
        endTime: "07:00 PM",
      },
      {
        dayOfWeek: "Saturday",
        startTime: "02:00 PM",
        endTime: "09:00 PM",
      },
    ],
    blockedTimeSlots: [],
  },
  {
    fullName: "Service Provider 4",
    email: "provider4@example.com",
    password: "hashedpassword",
    address: "Argao, Cebu",
    role: "service_provider",
    profile: {
      firstName: "Provider",
      lastName: "User 4",
      contactNumber: "987-654-3213",
      location: "Argao, Cebu",
      description: "Fitness trainer offering personalized training sessions.",
      profileImg: "https://randomuser.me/api/portraits/women/4.jpg",
    },
    ServiceCategory: ["Personal Fitness Training"],
    availability: [
      {
        dayOfWeek: "Wednesday",
        startTime: "07:00 AM",
        endTime: "01:00 PM",
      },
      {
        dayOfWeek: "Friday",
        startTime: "05:00 PM",
        endTime: "10:00 PM",
      },
    ],
    blockedTimeSlots: [],
  },
  {
    fullName: "Service Provider 5",
    email: "provider5@example.com",
    password: "hashedpassword",
    address: "Argao, Cebu",
    role: "service_provider",
    profile: {
      firstName: "Provider",
      lastName: "User 5",
      contactNumber: "987-654-3214",
      location: "Argao, Cebu",
      description: "Event planner with a creative touch.",
      profileImg: "https://randomuser.me/api/portraits/women/5.jpg",
    },
    ServiceCategory: ["Event Planning"],
    availability: [
      {
        dayOfWeek: "Thursday",
        startTime: "12:00 PM",
        endTime: "06:00 PM",
      },
      {
        dayOfWeek: "Saturday",
        startTime: "10:00 AM",
        endTime: "04:00 PM",
      },
    ],
    blockedTimeSlots: [],
  },
];

export const serviceCategories = [
  {
    name: "Plumbing",
    description: "Fixing and repairing plumbing systems.",
    slug: "plumbing",
  },
  {
    name: "Electrical Repair",
    description: "Repairing electrical systems and appliances.",
    slug: "electrical-repair",
  },
  {
    name: "Makeup Services",
    description: "Professional makeup for various occasions.",
    slug: "makeup-services",
  },
  {
    name: "Personal Fitness Training",
    description: "Customized fitness training sessions.",
    slug: "personal-fitness-training",
  },
  {
    name: "Event Planning",
    description: "Planning and organizing events.",
    slug: "event-planning",
  },
  {
    name: "Computer Repair",
    description: "Fixing and troubleshooting computer issues.",
    slug: "computer-repair",
  },
  {
    name: "Lawn Maintenance",
    description: "Maintaining and caring for lawns.",
    slug: "lawn-maintenance",
  },
  {
    name: "Graphic Design",
    description: "Creating visual content and designs.",
    slug: "graphic-design",
  },
  {
    name: "Pet Sitting",
    description: "Taking care of pets in the owner's absence.",
    slug: "pet-sitting",
  },
  {
    name: "Language Classes",
    description: "Teaching languages to individuals or groups.",
    slug: "language-classes",
  },
  // Add more service categories as needed
];
